<?php

namespace SiteBundle\Repository;

/**
 * PlatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatsRepository extends \Doctrine\ORM\EntityRepository
{
}
